
if &compatible
	set nocompatible
endif

let g:rc_dir = expand('~/.vim/rc') 

" スクリプトのロード
" name: スクリプトのファイル名
function! s:source_rc(name)
	let path = resolve(g:rc_dir . '/' . a:name)
	execute 'source' fnameescape(path)
endfunction

augroup MyAutoCmd
  autocmd!
augroup END

" dein settings
call s:source_rc('dein.rc.vim')
" View settings
call s:source_rc('view.rc.vim')
" Key mappings
call s:source_rc('mappings.rc.vim')
" Edit settings
call s:source_rc('edit.rc.vim')

"}}}
" matchit
source $VIMRUNTIME/macros/matchit.vim

set helplang=ja 
