#! /bin/sh

brew update

# for binary only
brew tap homebrew/binary || true
# for OSX default
brew tap homebrew/dupes || true
# for multiple versions
brew tap homebrew/versions || true
# for Ricty Font
brew tap sanemat/font || true
# for Peco
brew tap peco/peco || true

# for GUI Applications
brew install caskroom/cask/brew-cask

brew install autoconf
brew install automake
brew install libtool
brew install pkg-config

brew install convmv
brew install nkf
brew install p7zip
brew install w3m
brew install tree
brew install wget
brew install curl
brew install ssh-copy-id
brew install cmigemo

# VCS(git)
brew install git
brew install git-flow
brew install git-now
brew install tig
# gitignore 
brew install gibo

# VCS(Subversion)
brew install subversion

# zsh
brew install zsh
brew install zsh-completions
brew install autojump
# tap:peco/peco
brew install peco
brew install migemogrep

# ag
brew install the_silver_searcher

# tmux
brew install tmux
brew install reattach-to-user-namespace

# for X Application
brew cask install xquartz
# Ricty Font(tap: sanemat/font)
brew install ricty

# for Ruby
brew install rbenv
brew install ruby-build
brew install rbenv-binstubs
brew install rbenv-default-gems
brew install rbenv-gem-rehash

#brew install apple-gcc42
brew install readline
#brew link readline
brew install openssl
brew install iconv
brew link iconv --force
brew install libxml2
brew link libxml2 --force
brew install libxslt
brew link libxslt --force
#install ngnix
#install passenger

# for Rails
brew install graphicsmagick
brew install imagemagick

# Databases
brew install postgresql
brew install mariadb
brew install sqlite

brew install graphviz

# for Python
brew install pyenv
brew install pyenv-virtualenv

# for Node
brew install nodebrew

# ------------------------------------------------------------ 
# GUI Applications

# AppCleaner
brew cask install appcleaner

# yet another terminal
brew cask install iterm2

# Touch-Pad extension
brew cask install bettertouchtool

# Finder extension
brew cask install xtrafinder

# key remap
brew cask install karabiner

# reverse mouse scroll
brew cask install scroll-reverser

# GUI for git
brew cask install sourcetree

# Web Browser
brew cask install google-chrome

# markdown editor
brew cask install mou

# vagrant
brew cask install virtualbox
brew cask install vagrant

# Packet Analyzer
brew cask install wireshark
# blue light cut
brew cask install flux
# eclipse
brew cask install java
# eclipse
brew cask install eclipse-ide
# dropbox
brew cask install dropbox
# omnifocus
brew cask install omnifocus
# cheatsheet
brew cask install cheatsheet
# toolbar calendar
brew cask install fantastical

# QuickLook Plugin
brew cask install quicklook-json
brew cask install qlmarkdown
brew cask install qlstephen
brew cask install quicklook-csv
brew cask install betterzipql
brew cask install qlcolorcode

# Launcher
brew cask install alfred
brew cask alfred link

brew cleanup

