# PATH settings.
typeset -U path
PATH=/usr/local/bin:$PATH
PATH=/Applications/MacVim.app/Contents/MacOS:$PATH
PATH=~/dotfiles/bin:$PATH
export PATH
# PostgreSQL settings.
PGDATA=/usr/local/var/postgres
export PGDATA

